// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBMttRD-1s0WaAlwznGXCvLKGstAtUhgY',
    appId: '1:639114312267:web:5b1476178de61763452bce',
    messagingSenderId: '639114312267',
    projectId: 'mira-66606',
    authDomain: 'mira-66606.firebaseapp.com',
    storageBucket: 'mira-66606.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfB_5zNAJ_ellOOsN5HvUEsAVEfTZj9CA',
    appId: '1:639114312267:android:73970d31a89959f6452bce',
    messagingSenderId: '639114312267',
    projectId: 'mira-66606',
    storageBucket: 'mira-66606.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBMttRD-1s0WaAlwznGXCvLKGstAtUhgY',
    appId: '1:639114312267:web:263fb56570699054452bce',
    messagingSenderId: '639114312267',
    projectId: 'mira-66606',
    authDomain: 'mira-66606.firebaseapp.com',
    storageBucket: 'mira-66606.firebasestorage.app',
  );
}
